FROM python:3.11-slim-bullseye@sha256:6988e45203d296f2bc89f171995487f388fc18f1cb23110c6521eb3dcca369a9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements/py311-django41.txt .
RUN python -m pip install -r py311-django41.txt
WORKDIR /