FROM python:3.10-slim-bullseye@sha256:0b491b2ba21136d41c7a44ed6552ec5fc4ccd0d0f10f1fc64584f03b9d1dd90f
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements/py310-django41.txt .
RUN python -m pip install -r py310-django41.txt
WORKDIR /