FROM python:3.10-slim-bullseye@sha256:2674abed3e7ffff21501d1a5ca773920c2ed6d2087a871fd07799ff029c909c2
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements/py310-django40.txt .
RUN python -m pip install -r py310-django40.txt
WORKDIR /