FROM python:3.11-slim-bullseye@sha256:7f0ea9ea95d32db6ee8f4973aa76d777923b0cdd83ebec6fd63a20fc7d08f4cf
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements/py311-django42.txt .
RUN python -m pip install -r py311-django42.txt
WORKDIR /