FROM python:3.11-slim-bullseye@sha256:08ef1d5c4e0c05244f0971150437c57f6c79863345e549dbaebaf1b61f56bdf5
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements/py311-django42.txt .
RUN python -m pip install -r py311-django42.txt
WORKDIR /